"""Generalization evaluation across multiple traffic density configurations.

Loads a trained model and evaluates it across all density variant configs
(generated by ``generate_density_configs.py``) or uses runtime density
multipliers.  Compares RL agent performance against the fixed-time baseline
per configuration.

Usage:
    python scripts/evaluate_generalization.py --config config.yaml \\
        --model results/models/best_model.h5 --mode variants
"""

import os
import sys
import json
import yaml
import argparse
import numpy as np
from tqdm import tqdm

sys.path.append(os.path.join(os.path.dirname(__file__), ".."))

from src.utils.logger import setup_logger, get_logger
from src.environment.sumo_env import MultiAgentSumoEnv

logger = get_logger(__name__)


def _create_agent(algorithm: str, obs_dim: int, action_dim: int, config: dict):
    """Instantiate the appropriate agent.

    Args:
        algorithm: ``"dqn"`` or ``"ppo"``.
        obs_dim: Observation dim.
        action_dim: Action dim.
        config: Config dict.

    Returns:
        Agent instance.
    """
    if algorithm == "dqn":
        from src.agents.dqn_agent import DQNAgent
        return DQNAgent(obs_dim, action_dim, config)
    else:
        from src.agents.ppo_agent import PPOAgent
        device = config["experiment"].get("device", "cpu")
        return PPOAgent(obs_dim, action_dim, config, device)


def _run_single_eval(agent, config: dict, num_episodes: int = 3) -> dict:
    """Run evaluation on a single config and return metrics.

    Args:
        agent: Loaded agent.
        config: Config dict (with modified sumo.cfg_file or density_multiplier).
        num_episodes: Episodes to average over.

    Returns:
        Dict with avg metrics.
    """
    env = MultiAgentSumoEnv(config)
    all_waiting = []
    all_queue = []
    all_reward = []

    for ep in range(num_episodes):
        observations, _ = env.reset()
        ep_reward = {ts_id: 0.0 for ts_id in env.ts_ids}
        ep_waiting = []
        ep_queue = []
        done = False

        while not done:
            actions = {}
            for ts_id in env.ts_ids:
                action, _, _ = agent.select_action(observations[ts_id], deterministic=True)
                actions[ts_id] = action

            observations, rewards, dones, _, infos = env.step(actions)
            done = dones["__all__"]

            ep_waiting.append(sum(infos[t]["waiting_time"] for t in env.ts_ids))
            ep_queue.append(sum(infos[t]["queue"] for t in env.ts_ids))
            for ts_id in env.ts_ids:
                ep_reward[ts_id] += rewards[ts_id]

        all_waiting.append(float(np.mean(ep_waiting)))
        all_queue.append(float(np.mean(ep_queue)))
        all_reward.append(float(np.mean(list(ep_reward.values()))))

    env.close()
    return {
        "avg_waiting_time": float(np.mean(all_waiting)),
        "avg_queue": float(np.mean(all_queue)),
        "avg_reward": float(np.mean(all_reward)),
    }


def evaluate_generalization(
    config_path: str,
    model_path: str,
    mode: str = "runtime",
    episodes_per_config: int = 3,
    output_dir: str = None,
) -> dict:
    """Evaluate generalization across density configurations.

    Args:
        config_path: Path to base YAML config.
        model_path: Path to trained model weights.
        mode: ``"variants"`` (use generated route files) or ``"runtime"``
              (use density_multiplier at runtime).
        episodes_per_config: Episodes per density configuration.
        output_dir: Output directory. Defaults to ``results/generalization/``.

    Returns:
        Summary dict of all results.
    """
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)

    log_dir = config["experiment"]["log_dir"]
    if output_dir is None:
        output_dir = f"{log_dir}/generalization"
    os.makedirs(output_dir, exist_ok=True)
    setup_logger(log_dir=log_dir, log_level="INFO")

    algorithm = config["training"].get("algorithm", "dqn")
    multipliers = config.get("density_variants", {}).get(
        "multipliers", [0.25, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.5, 1.75, 2.0]
    )

    logger.info("=" * 60)
    logger.info("Generalization Evaluation")
    logger.info("Algorithm: %s | Model: %s | Mode: %s", algorithm.upper(), model_path, mode)
    logger.info("Density multipliers: %s", multipliers)
    logger.info("=" * 60)

    # Create agent once with base config to get dimensions
    env_tmp = MultiAgentSumoEnv(config)
    obs_tmp, _ = env_tmp.reset()
    obs_dim = len(obs_tmp[list(obs_tmp.keys())[0]])
    action_dim = env_tmp.action_space.n
    env_tmp.close()

    agent = _create_agent(algorithm, obs_dim, action_dim, config)
    agent.load(model_path)
    logger.info("Model loaded from %s", model_path)

    # Load baseline results if available
    baseline_path = f"{log_dir}/baseline/baseline_results.json"
    baseline_data = None
    if os.path.exists(baseline_path):
        with open(baseline_path, "r") as f:
            baseline_data = json.load(f)
        logger.info("Baseline data loaded from %s", baseline_path)

    results = []
    maps_dir = os.path.dirname(config["sumo"]["cfg_file"])

    for mult in tqdm(multipliers, desc="Density configs"):
        tag = f"{mult:.2f}x"
        variant_config = json.loads(json.dumps(config))  # deep copy

        if mode == "variants":
            variant_cfg_path = os.path.join(maps_dir, "density_variants", f"sumo_{tag}.sumocfg")
            if os.path.exists(variant_cfg_path):
                variant_config["sumo"]["cfg_file"] = variant_cfg_path
            else:
                logger.warning("Variant config not found: %s — using runtime scaling", variant_cfg_path)
                variant_config["sumo"]["density_multiplier"] = mult
        else:
            variant_config["sumo"]["density_multiplier"] = mult

        logger.info("Evaluating density=%s…", tag)
        metrics = _run_single_eval(agent, variant_config, episodes_per_config)

        entry = {
            "multiplier": mult,
            "tag": tag,
            **metrics,
        }

        # Compare to baseline if available
        if baseline_data:
            baseline_wait = baseline_data["avg_waiting_time"]
            if baseline_wait > 0:
                improvement = (baseline_wait - metrics["avg_waiting_time"]) / baseline_wait * 100
                entry["improvement_pct"] = round(improvement, 2)

        results.append(entry)
        logger.info(
            "  %s | AvgWait=%.1f | AvgQueue=%.1f | Reward=%.2f%s",
            tag, metrics["avg_waiting_time"], metrics["avg_queue"], metrics["avg_reward"],
            f" | Improvement={entry.get('improvement_pct', 'N/A')}%" if "improvement_pct" in entry else "",
        )

    summary = {
        "algorithm": algorithm,
        "model_path": model_path,
        "mode": mode,
        "episodes_per_config": episodes_per_config,
        "results": results,
    }

    # Print summary table
    logger.info("=" * 60)
    logger.info("Generalization Results:")
    logger.info("%-8s | %-12s | %-10s | %-10s | %-12s", "Density", "AvgWait", "AvgQueue", "Reward", "Improv. %")
    logger.info("-" * 60)
    for r in results:
        logger.info(
            "%-8s | %-12.1f | %-10.1f | %-10.2f | %-12s",
            r["tag"], r["avg_waiting_time"], r["avg_queue"], r["avg_reward"],
            f"{r['improvement_pct']:.1f}%" if "improvement_pct" in r else "N/A",
        )
    logger.info("=" * 60)

    # Save
    out_path = os.path.join(output_dir, "generalization_results.json")
    with open(out_path, "w") as f:
        json.dump(summary, f, indent=2)
    logger.info("Results saved to %s", out_path)

    return summary


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Evaluate RL agent generalization across traffic densities"
    )
    parser.add_argument("--config", type=str, default="config.yaml",
                        help="Path to config file")
    parser.add_argument("--model", type=str, required=True,
                        help="Path to trained model weights")
    parser.add_argument("--mode", type=str, default="runtime", choices=["variants", "runtime"],
                        help="Use pre-generated variant configs or runtime density scaling")
    parser.add_argument("--episodes", type=int, default=3,
                        help="Episodes per density configuration")
    parser.add_argument("--output-dir", type=str, default=None,
                        help="Output directory")
    args = parser.parse_args()

    evaluate_generalization(args.config, args.model, args.mode, args.episodes, args.output_dir)
